/*
 * Timer_config.h
 *
 * Created: 3/26/2023 2:16:15 PM
 *  Author: mohamed abdelslam
 */ 


#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/* options for timer0 mode: 
  OVER_FLOW_MODE
  PHASE_CORRECT_PWM_MODE
  CTC_MODE
  FAST_PWM_MODE
 */
#define TIMER0_MODE    OVER_FLOW_MODE  

/* options for timer0 clock
NO_CLOCK_SOURCE
CPU_CLOCK
CPU_DIV_BY_8
CPU_DIV_BY_64
CPU_DIV_BY_256
CPU_DIV_BY_1024
EXTERNAL_FALLING_EDGE
EXTERNAL_RISING_EDEG
 */
#define TIMER0_CLOCK     CPU_DIV_BY_1024     

/* select option
OC0_DISCONNECTED
TOGG_OC0_ON_COMP_MATCH
CLR_OC0_ON_COMP_MATCH
SET_OC0_ON_COMP_MATCH
 */
#define COMPARE_OUT_MODE    CLR_OC0_ON_COMP_MATCH  
/*select option :
OC0_ENABLED
OC0_DISABLED
 */
#define OC0_STATUS       OC0_DISABLED

/* options for timer2 clock source types
T2_CPU_CLOCK
T2_EXTERNAL_CRYSTAL_ON_TOSC1
 */
#define TIMER2_CLOCK_SOURCE_TYPE       CPU_CLOCK

/* options for timer2 clock source: 
NO_CLOCK_SOURCE
TIMER2_SOURCE_CLOCK
TIMER2_SOURCE_CLOCK_DIV_BY_8
TIMER2_SOURCE_CLOCK_DIV_BY_32
TIMER2_SOURCE_CLOCK_DIV_BY_64
TIMER2_SOURCE_CLOCK_DIV_BY_128
TIMER2_SOURCE_CLOCK_DIV_BY_256
TIMER2_SOURCE_CLOCK_DIV_BY_1024
*/
#define TIMER2_CLOCK     NO_CLOCK_SOURCE  

/* options for timer2 mode: 
  OVER_FLOW_MODE
  PHASE_CORRECT_PWM_MODE
  CTC_MODE
  FAST_PWM_MODE
 */
#define TIMER2_MODE    OVER_FLOW_MODE 

/* select option
OC2_DISCONNECTED
TOGG_OC2_ON_COMP_MATCH
CLR_OC2_ON_COMP_MATCH
SET_OC2_ON_COMP_MATCH
 */
#define TIMER2_COMPARE_OUT_MODE    CLR_OC0_ON_COMP_MATCH 

#define OC2_STATUS       OC2_DISABLED

#define TIMER1_CLOCK     CPU_CLOCK 

#define TIMER1_MODE      FAST_PWM_ICR1

#define OC1A_STATUS   OC1A_DISABLED
#define OC1B_STATUS   OC1B_DISABLED

/* options: 
 ICU_NOISE_CANCELLER_EN
 ICU_NOISE_CANCELLER_DIS
  */
#define ICU_NOISE_CANCELLER_STATUS      ICU_NOISE_CANCELLER_DIS

/* options :
ICU_FALLING_EDGE
ICU_RISING_EDGE
*/
#define ICU_EDGE  ICU_RISING_EDGE 
 
#endif /* TIMER_CONFIG_H_ */